ktor:
  development: true
  deployment:
    port: 8000
  application:
    modules:
      - com.vb4.ApplicationKt.module
  jwt:
    secret:
      "secret"
    audience:
      "audience"
    issuer:
      "issuer"
    realm:
      "castellaRealm"
    expiredSecond:
      "60000"
